# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
  adapters:
    expense_adapter:
      local:
        directory: '%kernel.cache_dir%/storage/expenses'

  filesystems:
    expense_filesystem:
      adapter: expense_adapter
      alias: League\Flysystem\Filesystem
