security:
    encoders:
        App\Entity\User:
            algorithm: auto


    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path: /
                  # by default, the feature is enabled by checking a
                  # checkbox in the login form (see below), uncomment the
                  # following line to always enable it.
                  #always_remember_me: true

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # Allow Logged-in and Anonymous users to the login page
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # All other pages require the user to be authenticated, even by session cookie
        - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED }

    # Add role inheritance so users only need one role assigned to them
    role_hierarchy:
        ROLE_ADMIN: [ROLE_APPROVER, ROLE_ACCOUNTANT, ROLE_USER]
        ROLE_APPROVER: [ROLE_ACCOUNTANT, ROLE_USER]
        ROLE_ACCOUNTANT: [ROLE_USER]